import { StyleSheet } from 'react-native';
import { borderRadius, colors, shadows, spacing, typography } from '../styles/theme';

const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.xl,
    paddingTop: spacing.base,
    paddingHorizontal: spacing.base,
    paddingBottom: spacing.base,
    borderWidth: 1,
    borderColor: colors.border.strong,
    ...shadows.lg,
  },
  compactContainer: {
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.full,
    minHeight: 56,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.navigation.tabBarBorder,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...shadows.lg,
  },
  sheetCompactContainer: {
    backgroundColor: colors.background.secondary,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    width: '100%',
    alignSelf: 'stretch',
    marginHorizontal: 0,
    borderTopWidth: 1,
    borderTopColor: colors.border.strong,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    paddingHorizontal: spacing.base,
    paddingTop: spacing.sm,
    paddingBottom: spacing.base,
    ...shadows.lg,
  },
  sheetAnimatedWrapper: {
    width: '100%',
    alignSelf: 'stretch',
    overflow: 'hidden',
  },
  sheetAnimatedWrapperCompact: {
    justifyContent: 'flex-end',
  },
  sheetAnimatedWrapperClosing: {
    backgroundColor: colors.background.secondary,
    borderTopWidth: 1,
    borderTopColor: colors.border.strong,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
  },
  sheetCompactRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sheetCompactMain: {
    flex: 1,
    marginRight: spacing.sm,
  },
  sheetHandle: {
    width: 44,
    height: 5,
    borderRadius: borderRadius.full,
    backgroundColor: colors.border.strong,
    alignSelf: 'center',
    marginBottom: spacing.sm,
  },
  compactContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  compactIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm + 2,
  },
  compactTextContainer: {
    flex: 1,
  },
  sheetCompactTextContainer: {
    marginTop: 5,
  },
  compactStatus: {
    color: colors.text.primary,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.base,
  },
  compactInfo: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.sm,
    marginTop: 2,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.base,
  },
  headerButtons: {
    flexDirection: 'row',
  },
  chatHeaderButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    position: 'relative',
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.strong,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  chatActionButton: {
    width: 30,
    height: 30,
    borderRadius: borderRadius.full,
    position: 'relative',
    borderWidth: 1,
    borderColor: colors.border.strong,
    backgroundColor: colors.background.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  chatUnreadDot: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 9,
    height: 9,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.warning,
    borderWidth: 1,
    borderColor: colors.background.secondary,
  },
  chatUnreadDotCompact: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 8,
    height: 8,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.warning,
    borderWidth: 1,
    borderColor: colors.background.secondary,
  },
  title: {
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
    color: colors.text.primary,
  },
  refreshButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.strong,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  collapseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.background.tertiary,
    borderWidth: 1,
    borderColor: colors.border.strong,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bodyScroll: {
    flexGrow: 0,
  },
  bodyContent: {
    paddingBottom: spacing.xs,
  },
  driverInfoContainer: {
    backgroundColor: colors.background.panel,
    borderRadius: borderRadius.lg,
    padding: spacing.base,
    marginBottom: spacing.base,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  driverInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  driverAvatar: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  driverTextInfo: {
    flex: 1,
    marginLeft: 10,
  },
  driverName: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.primary,
  },
  vehicleInfo: {
    fontSize: typography.fontSize.sm,
    color: colors.text.secondary,
  },
  driverRating: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  ratingText: {
    color: colors.gold,
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  tapIndicator: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.full,
    borderWidth: 1,
    borderColor: colors.border.strong,
    width: 30,
    height: 30,
  },
  sheetContainer: {
    width: '100%',
    alignSelf: 'stretch',
    marginHorizontal: 0,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 0,
    borderTopWidth: 1,
    borderTopColor: colors.border.strong,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.18,
  },
  statusContainer: {
    marginBottom: spacing.base,
  },
  statusStep: {
    flexDirection: 'row',
    marginBottom: spacing.base,
  },
  statusIconContainer: {
    alignItems: 'center',
    marginRight: spacing.base,
  },
  statusDot: {
    width: 32,
    height: 32,
    borderRadius: borderRadius.circle,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  activeDot: {
    backgroundColor: colors.primary,
  },
  inactiveDot: {
    backgroundColor: colors.border.strong,
  },
  currentDot: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  statusTextContainer: {
    flex: 1,
  },
  statusLabel: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.medium,
  },
  activeLabel: {
    color: colors.text.primary,
  },
  inactiveLabel: {
    color: colors.text.subtle,
  },
  currentLabel: {
    fontWeight: typography.fontWeight.bold,
  },
  statusDescription: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.sm,
    marginTop: spacing.xs,
  },
  statusLine: {
    width: 2,
    height: 24,
  },
  activeLine: {
    backgroundColor: colors.primary,
  },
  inactiveLine: {
    backgroundColor: colors.border.strong,
  },
  photoButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  photoButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.elevated,
    borderWidth: 1,
    borderColor: colors.border.strong,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.base,
    borderRadius: borderRadius.full,
  },
  photoButtonText: {
    color: colors.text.primary,
    marginLeft: spacing.xs,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  loadingContainer: {
    minHeight: 56,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.full,
    borderWidth: 1,
    borderColor: colors.navigation.tabBarBorder,
    flexDirection: 'row',
    ...shadows.lg,
  },
  loadingText: {
    color: colors.text.secondary,
    marginLeft: spacing.sm,
    fontSize: typography.fontSize.base,
  },
  errorContainer: {
    minHeight: 56,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.full,
    borderWidth: 1,
    borderColor: colors.navigation.tabBarBorder,
    flexDirection: 'row',
    ...shadows.lg,
  },
  errorText: {
    color: colors.error,
    marginLeft: spacing.sm,
    fontSize: typography.fontSize.base,
  },
});

export default styles;
