import { Dimensions, StyleSheet } from 'react-native';
import { borderRadius, colors, spacing, typography } from '../styles/theme';

const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get('window');

const styles = StyleSheet.create({
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.black,
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: colors.background.secondary,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: spacing.md,
    elevation: 10,
    overflow: 'hidden',
  },
  handleArea: {
    paddingTop: spacing.base,
    paddingBottom: spacing.sm,
    alignItems: 'center',
  },
  handleBar: {
    width: spacing.xxxl - spacing.sm,
    height: spacing.xs,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.border.inverse,
  },
  timerSection: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.sm,
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  timerText: {
    fontSize: typography.fontSize.xxxl,
    fontWeight: typography.fontWeight.bold,
    marginLeft: spacing.sm,
    letterSpacing: 1,
  },
  timerBar: {
    height: spacing.sm - 2,
    backgroundColor: colors.background.input,
    borderRadius: borderRadius.xs,
    overflow: 'hidden',
  },
  timerFill: {
    height: '100%',
    borderRadius: borderRadius.xs,
  },
  earningsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.base,
  },
  earningsAmount: {
    fontSize: typography.fontSize.xxxl + 4,
    fontWeight: typography.fontWeight.bold,
    color: colors.text.primary,
    letterSpacing: -1,
  },
  earningsNote: {
    fontSize: typography.fontSize.sm,
    color: colors.text.tertiary,
    marginTop: spacing.xs / 2,
  },
  vehicleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warningLight,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.xl,
  },
  vehicleText: {
    color: colors.warning,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    marginLeft: spacing.xs,
  },
  addressesSection: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.md,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm - 2,
  },
  addressDot: {
    width: spacing.md,
    height: spacing.md,
    borderRadius: spacing.md / 2,
    marginRight: spacing.md,
  },
  addressText: {
    flex: 1,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    color: colors.text.primary,
  },
  addressConnector: {
    width: 2,
    height: spacing.base,
    backgroundColor: colors.border.strong,
    marginLeft: spacing.xs + 1,
  },
  helpBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warningLight,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.sm,
  },
  helpText: {
    color: colors.warning,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    marginLeft: spacing.sm,
  },
  buttonsRow: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  declineBtn: {
    flex: 1,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.elevated,
    borderRadius: borderRadius.full,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  declineTxt: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
  },
  acceptBtn: {
    flex: 1,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: borderRadius.full,
  },
  acceptTxt: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  detailsScroll: {
    flex: 1,
  },
  detailsHint: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  hintLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border.strong,
  },
  hintText: {
    color: colors.text.muted,
    fontSize: typography.fontSize.sm,
    marginHorizontal: spacing.md,
  },
  scheduledBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primaryLight,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.md,
  },
  scheduledText: {
    color: colors.primary,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.sm,
  },
  locCard: {
    backgroundColor: colors.background.input,
    borderRadius: borderRadius.md,
    padding: spacing.base,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  locCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  locDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: spacing.sm,
  },
  locLabel: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  locAddress: {
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    lineHeight: 22,
    marginBottom: spacing.xs,
  },
  locDetailsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  locDetailText: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.sm,
  },
  locNotes: {
    color: colors.text.muted,
    fontSize: typography.fontSize.sm,
    fontStyle: 'italic',
    marginTop: spacing.xs,
  },
  detailSection: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.base,
  },
  detailTitle: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    marginBottom: spacing.md,
  },
  itemCard: {
    backgroundColor: colors.background.input,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  itemCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemName: {
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    flex: 1,
  },
  itemWeight: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.sm,
  },
  itemDims: {
    color: colors.text.muted,
    fontSize: typography.fontSize.sm,
    marginTop: spacing.xs,
  },
  itemPhoto: {
    width: spacing.xxxl + spacing.md,
    height: spacing.xxxl + spacing.md,
    borderRadius: borderRadius.sm,
    marginRight: spacing.sm,
    backgroundColor: colors.background.elevated,
  },
  fallbackPhoto: {
    width: spacing.xxxl + spacing.xl,
    height: spacing.xxxl + spacing.xl,
    borderRadius: borderRadius.md,
    marginRight: spacing.sm,
    marginLeft: spacing.lg,
    backgroundColor: colors.background.input,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  customerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.input,
    padding: spacing.base,
    borderRadius: borderRadius.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.base,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  customerPhoto: {
    width: spacing.xxxl - spacing.sm,
    height: spacing.xxxl - spacing.sm,
    borderRadius: (spacing.xxxl - spacing.sm) / 2,
    backgroundColor: colors.background.elevated,
  },
  customerInfo: {
    marginLeft: spacing.md,
  },
  customerName: {
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    marginBottom: 2,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.xs,
  },
  priceCard: {
    backgroundColor: colors.background.input,
    borderRadius: borderRadius.md,
    padding: spacing.base,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.base,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  priceLabel: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.base,
  },
  priceVal: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.base,
  },
  priceTotalRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border.strong,
    paddingTop: spacing.sm,
    marginBottom: 0,
  },
  priceTotalLabel: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
  },
  priceTotalVal: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  photoViewerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.92)',
    zIndex: 1000,
    justifyContent: 'center',
  },
  photoViewerPage: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoViewerImage: {
    width: SCREEN_WIDTH - spacing.xxl * 2,
    height: SCREEN_HEIGHT * 0.65,
    borderRadius: borderRadius.md,
  },
  photoViewerDots: {
    position: 'absolute',
    bottom: spacing.xxxl + spacing.xxl,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  photoViewerDot: {
    width: spacing.sm,
    height: spacing.sm,
    borderRadius: borderRadius.xs,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  photoViewerDotActive: {
    backgroundColor: colors.white,
    width: spacing.xl,
  },
  photoViewerClose: {
    position: 'absolute',
    top: spacing.xxxl + spacing.md,
    right: spacing.lg,
    width: spacing.xxxl + spacing.sm,
    height: spacing.xxxl + spacing.sm,
    borderRadius: borderRadius.xl,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
