import { StyleSheet } from 'react-native';
import { borderRadius, colors, shadows, spacing, typography } from '../../styles/theme';

const ACTIVE_TRIP_BUTTON_COLOR = "#F6C74A";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  headerLogo: {
    height: 20,
    resizeMode: "contain",
    ...shadows.lg,
  },
  geoNoticeContainer: {
    position: "absolute",
    left: spacing.lg,
    right: spacing.lg,
    zIndex: 30,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderRadius: borderRadius.md,
    backgroundColor: colors.background.warningSubtle,
    borderWidth: 1,
    borderColor: colors.warning,
  },
  geoNoticeText: {
    flex: 1,
    color: colors.text.primary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    lineHeight: 18,
  },
  phoneNoticeContainer: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
    alignItems: "center",
  },
  phoneNoticeActionChip: {
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs,
  },
  phoneNoticeActionText: {
    color: colors.text.primary,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
  },
  floatingTriggerContainer: {
    position: "absolute",
    bottom: 0,
    alignSelf: "center",
    paddingHorizontal: spacing.lg,
    zIndex: 20,
  },
  floatingTrigger: {
    backgroundColor: colors.background.tertiary,
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 56,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.base,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: colors.navigation.tabBarBorder,
  },
  floatingTriggerDisabled: {
    opacity: 0.78,
  },
  triggerIconCircle: {
    width: 32,
    height: 32,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.md,
  },
  triggerIconCircleDisabled: {
    backgroundColor: colors.warning,
  },
  floatingTriggerText: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.primary,
    flex: 1,
  },
  floatingTriggerTextDisabled: {
    color: colors.text.secondary,
  },
  triggerTimeBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background.secondary,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.sm - 2,
    borderRadius: borderRadius.full,
  },
  triggerTimeText: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
  },
  timeIconLeft: {
    marginRight: 4,
  },
  timeIconRight: {
    marginLeft: 4,
  },
  activeTripPulseWrap: {
    width: "100%",
  },
  activeTripTrigger: {
    backgroundColor: ACTIVE_TRIP_BUTTON_COLOR,
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 56,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    shadowColor: ACTIVE_TRIP_BUTTON_COLOR,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.42,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  activeTripSideSlot: {
    width: 34,
    justifyContent: "center",
  },
  activeTripSideSlotLeft: {
    alignItems: "flex-start",
  },
  activeTripSideSlotRight: {
    alignItems: "flex-end",
  },
  activeTripIconCircle: {
    width: 32,
    height: 32,
    borderRadius: borderRadius.circle,
    backgroundColor: "rgba(255,255,255,0.52)",
    alignItems: "center",
    justifyContent: "center",
  },
  activeTripTriggerText: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    color: colors.background.primary,
    flex: 1,
    textAlign: "center",
    paddingHorizontal: spacing.xxs,
  },
  activeTripOpenIndicator: {
    width: 32,
    height: 32,
    borderRadius: borderRadius.circle,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(10,10,31,0.14)",
  },
  searchingMarkerContainer: {
    width: 136,
    height: 136,
    alignItems: "center",
    justifyContent: "center",
  },
  searchingMarkerPulse: {
    backgroundColor: colors.transparent,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 999,
  },
  searchingMarkerCore: {
    position: "absolute",
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primaryDark,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 8,
  },
});

export default styles;
