import { Platform, StyleSheet } from 'react-native';
import { borderRadius, colors, spacing, typography } from '../../styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
  },
  loadingText: {
    marginTop: spacing.sm + 2,
    fontSize: typography.fontSize.md,
    color: colors.text.primary,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
    padding: spacing.lg,
  },
  errorText: {
    marginTop: spacing.lg,
    fontSize: typography.fontSize.md,
    color: colors.text.primary,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: spacing.lg,
    backgroundColor: colors.primary,
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: borderRadius.full,
  },
  retryButtonText: {
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  backButton: {
    position: 'absolute',
    left: spacing.lg,
    backgroundColor: colors.overlayDark,
    width: 40,
    height: 40,
    borderRadius: borderRadius.circle,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    borderWidth: 1,
    borderColor: colors.navigation.tabBarBorder,
  },
  driverMarker: {
    backgroundColor: colors.primary,
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: colors.white,
  },
  destinationMarker: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoCard: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    alignSelf: 'center',
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    overflow: 'hidden',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 10,
  },
  cardGradient: {
    padding: spacing.lg,
    paddingBottom: Platform.OS === 'ios' ? spacing.xxl + spacing.sm : spacing.lg,
  },
  destinationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.base - 1,
  },
  destinationTitle: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
    color: colors.text.primary,
  },
  destinationAddress: {
    fontSize: typography.fontSize.base,
    color: colors.text.muted,
    marginTop: 2,
    maxWidth: '75%',
  },
  etaBox: {
    backgroundColor: colors.primaryLight,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  etaTime: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
    color: colors.primary,
  },
  etaLabel: {
    fontSize: typography.fontSize.sm,
    color: colors.text.muted,
  },
  divider: {
    height: 1,
    backgroundColor: colors.navigation.tabBarBorder,
    marginVertical: spacing.base - 1,
  },
  customerInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.base - 1,
  },
  customerAvatarContainer: {
    width: 46,
    height: 46,
    borderRadius: 23,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: colors.navigation.tabBarBorder,
  },
  customerAvatarImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  customerDetails: {
    flex: 1,
    marginLeft: spacing.base - 1,
  },
  customerName: {
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.primary,
  },
  itemInfo: {
    fontSize: typography.fontSize.base,
    color: colors.text.muted,
    marginTop: 2,
  },
  callButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    position: 'relative',
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  callButtonUnreadDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 9,
    height: 9,
    borderRadius: borderRadius.circle,
    backgroundColor: colors.warning,
    borderWidth: 1,
    borderColor: colors.background.secondary,
  },
  actionContainer: {
    alignItems: 'center',
  },
  arriveButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: borderRadius.full,
    width: '100%',
    alignItems: 'center',
  },
  arriveButtonText: {
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  // Navigation instruction styles
  navigationContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    backgroundColor: 'transparent',
  },
  
  navigationHeader: {
    backgroundColor: colors.primaryDark,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
  },
  
  navigationHeaderContent: {
    alignItems: 'center',
  },
  
  distanceText: {
    fontSize: typography.fontSize.xxxl - spacing.xs,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
    marginBottom: 8,
  },
  
  instructionText: {
    fontSize: typography.fontSize.lg,
    color: colors.white,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 12,
  },
  
  directionArrows: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  
  // Floating overlay styles for navigation mode
  floatingBottomCard: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    alignSelf: 'center',
    zIndex: 9999,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    overflow: 'hidden',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 20,
  },
  
  closeNavButton: {
    position: 'absolute',
    right: spacing.lg,
    backgroundColor: colors.overlayDark,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10000,
    borderWidth: 2,
    borderColor: colors.navigation.tabBarBorder,
  },
  
  startNavButton: {
    position: 'absolute',
    right: spacing.lg,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: borderRadius.full,
    zIndex: 10,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  
  startNavText: {
    color: colors.white,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    marginLeft: spacing.sm - 2,
  },
});

export default styles;
