import { StyleSheet } from 'react-native';
import { borderRadius, colors, shadows, spacing, typography, zIndex } from '../../styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  topChrome: {
    backgroundColor: colors.background.primary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 5,
  },
  topChromeInner: {
    width: '100%',
    alignSelf: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.base,
    paddingBottom: spacing.sm,
    backgroundColor: colors.background.primary,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    flex: 1,
    textAlign: 'center',
  },
  closeButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressContainer: {
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.sm,
    backgroundColor: colors.background.primary,
  },
  progressBackground: {
    height: 4,
    backgroundColor: colors.border.strong,
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: spacing.sm,
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 2,
  },
  progressText: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
  },
  contentArea: {
    flex: 1,
  },
  contentAreaInner: {
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.base,
    alignItems: 'center',
    paddingBottom: spacing.xl,
  },
  stepContainer: {
    width: '100%',
    paddingTop: spacing.sm,
    alignItems: 'center',
  },
  stepIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  stepTitle: {
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  stepSubtitle: {
    fontSize: typography.fontSize.md,
    color: colors.text.tertiary,
    marginBottom: spacing.xl + spacing.sm,
    textAlign: 'center',
    lineHeight: typography.fontSize.md * typography.lineHeight.normal,
  },

  // Welcome content
  welcomeContent: {
    width: '100%',
    alignItems: 'center',
  },
  videoContainer: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
    backgroundColor: colors.black,
    marginBottom: spacing.lg,
  },
  video: {
    width: '100%',
    height: '100%',
  },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  playButton: {
    width: spacing.xxl * 2,
    height: spacing.xxl * 2,
    borderRadius: spacing.xxl,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: spacing.xs,
  },
  videoWatchedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.successLight,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.base,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.lg,
    gap: spacing.sm,
  },
  videoWatchedText: {
    color: colors.success,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.medium,
  },
  welcomeIconContainer: {
    width: 120,
    height: 120,
    backgroundColor: colors.background.elevated,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  welcomeTitle: {
    fontSize: typography.fontSize.xxxl - spacing.xs,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
    marginBottom: spacing.base,
    textAlign: 'center',
  },
  welcomeDescription: {
    fontSize: typography.fontSize.md,
    color: colors.text.tertiary,
    textAlign: 'center',
    lineHeight: typography.fontSize.md * typography.lineHeight.normal,
    marginBottom: spacing.xxl,
    paddingHorizontal: spacing.lg,
  },
  benefitsList: {
    width: '100%',
    paddingHorizontal: spacing.base,
    marginTop: spacing.lg,
  },
  benefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.tertiary,
    paddingVertical: spacing.base,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.md,
  },
  benefitText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.md,
  },

  // Form content
  formContent: {
    width: '100%',
    paddingTop: spacing.lg,
  },
  formDescription: {
    fontSize: typography.fontSize.md,
    color: colors.text.tertiary,
    textAlign: 'center',
    marginBottom: spacing.xxl,
    lineHeight: typography.fontSize.md * typography.lineHeight.normal,
  },
  inputContainer: {
    marginBottom: spacing.lg,
  },
  inputRow: {
    flexDirection: 'row',
    marginBottom: spacing.lg,
  },
  inputLabel: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginBottom: spacing.sm,
  },
  textInput: {
    backgroundColor: colors.background.input,
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: borderRadius.full,
    paddingVertical: spacing.base,
    paddingHorizontal: spacing.base,
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
  },
  lockedInput: {
    backgroundColor: colors.background.tertiary,
    borderColor: colors.border.strong,
    color: colors.text.tertiary,
    opacity: 0.7,
  },

  // Final content
  finalContent: {
    width: '100%',
    alignItems: 'center',
    paddingTop: spacing.lg,
  },
  finalIconContainer: {
    width: 100,
    height: 100,
    backgroundColor: colors.background.elevated,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  finalTitle: {
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
    marginBottom: spacing.base,
    textAlign: 'center',
  },
  finalDescription: {
    fontSize: typography.fontSize.md,
    color: colors.text.tertiary,
    textAlign: 'center',
    lineHeight: typography.fontSize.md * typography.lineHeight.normal,
    marginBottom: spacing.xxl,
    paddingHorizontal: spacing.lg,
  },
  securityFeatures: {
    width: '100%',
    marginBottom: spacing.xxl,
  },
  securityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.tertiary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.sm,
  },
  securityText: {
    color: colors.text.primary,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.medium,
    marginLeft: spacing.md,
  },
  finalNote: {
    backgroundColor: colors.background.tertiary,
    paddingVertical: spacing.base,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
    width: '100%',
  },
  finalNoteText: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.base,
    textAlign: 'center',
    lineHeight: typography.fontSize.base * typography.lineHeight.normal,
  },

  // Verification styles
  verificationFeatures: {
    marginTop: spacing.xl,
    marginBottom: spacing.xxl,
  },
  verificationItem: {
    flexDirection: 'row',
    marginBottom: spacing.xl,
    alignItems: 'flex-start',
  },
  verificationIcon: {
    width: spacing.xxxl,
    height: spacing.xxxl,
    backgroundColor: colors.successLight,
    borderRadius: spacing.xl,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.base,
  },
  verificationContent: {
    flex: 1,
  },
  verificationTitle: {
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  verificationText: {
    fontSize: typography.fontSize.base,
    color: colors.text.tertiary,
    lineHeight: typography.fontSize.base * typography.lineHeight.normal,
  },
  verifyButton: {
    backgroundColor: colors.success,
    paddingVertical: spacing.base,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    marginTop: spacing.lg,
  },
  verifyButtonDisabled: {
    backgroundColor: colors.text.subtle,
    opacity: 0.7,
  },
  verifyButtonSuccess: {
    backgroundColor: colors.success,
    opacity: 1,
  },
  verifyButtonText: {
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  verificationSuccess: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.successLight,
    padding: spacing.base,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.lg,
  },
  verificationSuccessText: {
    color: colors.success,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    marginLeft: spacing.sm,
  },
  verificationRejectedCard: {
    backgroundColor: `${colors.secondary}12`,
    borderWidth: 1,
    borderColor: `${colors.secondary}33`,
    borderRadius: borderRadius.lg,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    marginTop: spacing.md,
  },
  verificationRejectedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  verificationRejectedTitle: {
    marginLeft: spacing.sm,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.primary,
  },
  verificationRejectedText: {
    color: colors.text.secondary,
    fontSize: typography.fontSize.base,
    lineHeight: typography.fontSize.base * typography.lineHeight.relaxed,
  },
  verificationRejectedLink: {
    color: colors.primary,
    textDecorationLine: 'underline',
    fontWeight: typography.fontWeight.semibold,
  },
  loadingText: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.base,
    marginTop: spacing.sm,
  },

  // Bottom actions
  bottomActions: {
    flexDirection: 'row',
    paddingHorizontal: spacing.base,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    backgroundColor: colors.background.primary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 10,
    gap: spacing.md,
  },
  backActionButton: {
    flex: 1,
    backgroundColor: colors.border.strong,
    height: 56,
    justifyContent: 'center',
    borderRadius: borderRadius.full,
    alignItems: 'center',
  },
  backActionText: {
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
  },
  nextButton: {
    flex: 2,
    backgroundColor: colors.primary,
    height: 56,
    justifyContent: 'center',
    borderRadius: borderRadius.full,
    alignItems: 'center',
    ...shadows.primary,
  },
  nextButtonFull: {
    flex: 1,
  },
  nextButtonDisabled: {
    backgroundColor: colors.text.subtle,
    shadowOpacity: 0,
    elevation: 0,
  },
  nextButtonText: {
    color: colors.text.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  // Button loading container
  buttonLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Input validation styles
  textInputError: {
    borderColor: colors.secondary,
    borderWidth: 1,
  },
  inputHint: {
    color: colors.secondary,
    fontSize: typography.fontSize.xs,
    marginTop: spacing.xs,
  },

  // State Picker styles
  pickerButton: {
    backgroundColor: colors.background.input,
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: borderRadius.full,
    paddingVertical: spacing.base,
    paddingHorizontal: spacing.base,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
  },
  pickerButtonPlaceholder: {
    color: colors.text.subtle,
    fontSize: typography.fontSize.md,
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.base,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.strong,
  },
  pickerTitle: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
  },
  pickerList: {
    paddingHorizontal: spacing.base,
  },
  pickerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.base,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.strong,
  },
  pickerItemSelected: {
    backgroundColor: colors.primaryLight,
    marginHorizontal: -spacing.base,
    paddingHorizontal: spacing.base,
  },
  pickerItemText: {
    color: colors.white,
    fontSize: typography.fontSize.md,
  },
  pickerItemTextSelected: {
    color: colors.primary,
    fontWeight: typography.fontWeight.semibold,
  },
  suggestionsContainer: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: colors.background.tertiary,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border.default,
    marginTop: spacing.xs,
    maxHeight: 200,
    zIndex: zIndex.dropdown,
    elevation: 10,
    overflow: 'hidden',
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border.strong,
  },
  suggestionText: {
    flex: 1,
    color: colors.white,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.normal,
  },
  addressInputWrapper: {
    position: 'relative',
  },
  addressLoadingIndicator: {
    position: 'absolute',
    right: spacing.md,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInputWithLoader: {
    paddingRight: spacing.xxxl,
  },
  autoFilledBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.successLight,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.lg,
  },
  autoFilledText: {
    color: colors.success,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.sm,
    flex: 1,
    lineHeight: typography.fontSize.sm * typography.lineHeight.normal,
  },

  // Vehicle verification styles
  photoSection: {
    marginBottom: spacing.lg,
  },
  sectionLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  sectionLabel: {
    color: colors.white,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    flex: 1,
  },
  infoButton: {
    marginLeft: spacing.sm,
    padding: spacing.xs,
  },
  sectionHint: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.sm,
    marginBottom: spacing.md,
    lineHeight: typography.fontSize.sm * typography.lineHeight.normal,
  },
  photoCaptureSlot: {
    backgroundColor: colors.background.tertiary,
    borderWidth: 2,
    borderColor: colors.border.default,
    borderStyle: 'dashed',
    borderRadius: borderRadius.lg,
    height: 160,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  photoCaptureSlotFilled: {
    borderStyle: 'solid',
    borderColor: colors.success,
  },
  photoCaptureEmpty: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoCaptureText: {
    color: colors.text.subtle,
    fontSize: typography.fontSize.sm,
    marginTop: spacing.sm,
  },
  photoCapturePreview: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  photoRetakeOverlay: {
    position: 'absolute',
    bottom: spacing.sm,
    right: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
  },
  photoRetakeText: {
    color: colors.white,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.xs,
  },
  photoSlotWrapper: {
    position: 'relative',
  },
  photoDeleteButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    zIndex: 10,
    backgroundColor: colors.background.primary,
    borderRadius: borderRadius.full,
  },
  carPhotosRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  carPhotoSlotContainer: {
    flex: 1,
    alignItems: 'center',
  },
  carPhotoSlot: {
    width: '100%',
    height: 110,
    backgroundColor: colors.background.tertiary,
    borderWidth: 2,
    borderColor: colors.border.default,
    borderStyle: 'dashed',
    borderRadius: borderRadius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  carPhotoLabel: {
    textAlign: 'center',
    marginTop: spacing.xs,
    fontSize: typography.fontSize.xs,
    color: colors.text.tertiary,
  },
  carPhotoDeleteButton: {
    position: 'absolute',
    top: -6,
    right: -6,
    zIndex: 10,
    backgroundColor: colors.background.primary,
    borderRadius: borderRadius.full,
  },
  carPhotoRetakeOverlay: {
    position: 'absolute',
    bottom: spacing.xs,
    right: spacing.xs,
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: spacing.xs,
    borderRadius: borderRadius.full,
  },
  verifyVehicleButton: {
    backgroundColor: colors.info,
    paddingVertical: spacing.base,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: spacing.lg,
  },
  vehicleVerificationLoading: {
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  vehicleVerificationLoadingText: {
    color: colors.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    marginTop: spacing.md,
  },
  vehicleVerificationSubtext: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.sm,
    marginTop: spacing.xs,
  },
  vehicleVerificationErrorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${colors.secondary}15`,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.lg,
  },
  vehicleVerificationErrorText: {
    color: colors.secondary,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.sm,
    flex: 1,
  },
  retryLink: {
    color: colors.primary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    marginLeft: spacing.sm,
  },
  manualEntryNote: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    marginBottom: spacing.sm,
  },
  manualEntryNoteText: {
    color: colors.text.tertiary,
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.sm,
    flex: 1,
    lineHeight: typography.fontSize.sm * typography.lineHeight.normal,
  },
});

export default styles;
